package com.fc.ux.persistence.model;

// Generated Nov 23, 2015 7:03:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TFuelCompany generated by hbm2java
 */
@Entity
@Table(name = "busdevice")
public class BusDevice {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
	private Long busDeviceId;

	private Long busId;
    private Long deviceId;
	private String status;
	private Date addedDate;
    private Date statusChangedDate;
    private int addedByUserId;

    public Long getBusDeviceId() {
        return busDeviceId;
    }

    public void setBusDeviceId(Long busDeviceId) {
        this.busDeviceId = busDeviceId;
    }

    public Long getBusId() {
        return busId;
    }

    public void setBusId(Long busId) {
        this.busId = busId;
    }

    public Long getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getAddedDate() {
        return addedDate;
    }

    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }

    public Date getStatusChangedDate() {
        return statusChangedDate;
    }

    public void setStatusChangedDate(Date statusChangedDate) {
        this.statusChangedDate = statusChangedDate;
    }

    public int getAddedByUserId() {
        return addedByUserId;
    }

    public void setAddedByUserId(int addedByUserId) {
        this.addedByUserId = addedByUserId;
    }
}
