package com.fc.ux.persistence.model;

// Generated Nov 23, 2015 7:03:48 PM by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonBackReference;

import javax.persistence.*;
import java.util.Comparator;

/**
 * TFuelCompany generated by hbm2java
 */
@Entity
@Table(name = "routesection")
public class RouteSection implements Comparator<RouteSection> {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
	private int routeSectionId;

	//private int routeId;
	private int sectionNo;
	private String sectionName;

    @ManyToOne(targetEntity = Route.class)
    @JoinColumn(name = "routeId", nullable = false)
    @JsonBackReference
    private Route route;

    public Route getRoute() {
        return route;
    }

    public void setRoute(Route route) {
        this.route = route;
    }

    public int getSectionNo() {
        return sectionNo;
    }

    public void setSectionNo(int sectionNo) {
        this.sectionNo = sectionNo;
    }

    public String getSectionName() {
        return sectionName;
    }

    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }

    public int getRouteSectionId() {
        return routeSectionId;
    }

    public void setRouteSectionId(int routeSectionId) {
        this.routeSectionId = routeSectionId;
    }

    @Override
    public int compare(RouteSection o1, RouteSection o2) {
        return o1.getRouteSectionId() - o2.getRouteSectionId();
    }
}
